### PR TITLE
Port to windows and preserve linux compatibility, and focus on static lib creation used by xgboost

### PR DESCRIPTION
**Pull request by pseudotensor**

### CODE REVIEW

**Comment by tqchen** [comment]
do we need sln files? I assume only cmake files are needed?

**Comment by pseudotensor** [comment]
Everything is cleaned-up and squashed.  Please accept the PR when you are ready so I can fix the xgboost PR.

**Comment by piiswrong** [comment]
Are we going to upstream this?

**Comment by tqchen** [comment]
based on the comment, this is needed for windows support in xgboost. will remove this repo after the change becomes upstream in nccl

**Pull request merged**
